"""
Emergency Configuration for Women Safety CCTV System
Configure email and SMS settings for emergency notifications
"""

# Email Configuration
EMAIL_CONFIG = {
    'enabled': True,
    'smtp_server': 'smtp.gmail.com',
    'smtp_port': 587,
    'sender_email': 'women.safety.cctv@gmail.com',  # Change to your email
    'sender_password': 'your_app_password_here',    # Use app password for Gmail
    
    # Authority email addresses - ADD YOUR REAL CONTACTS HERE
    'authority_emails': [
        'police.emergency@city.gov',      # Local police emergency
        'security@building.com',          # Building security
        'safety.officer@company.com',     # Safety officer
        'emergency.contact@example.com'   # Additional emergency contact
    ]
}

# SMS Configuration (using Twilio as example)
SMS_CONFIG = {
    'enabled': True,
    'service': 'twilio',  # Options: 'twilio', 'textbelt', 'custom'
    
    # Twilio credentials - GET THESE FROM TWILIO CONSOLE
    'account_sid': 'your_twilio_account_sid_here',
    'auth_token': 'your_twilio_auth_token_here', 
    'from_phone': '+1234567890',  # Your Twilio phone number
    
    # Authority phone numbers - ADD YOUR REAL CONTACTS HERE
    'authority_phones': [
        '+1-911-000-0000',    # Emergency services
        '+1-555-0123',        # Security office
        '+1-555-0456',        # Safety officer
        '+1-555-0789'         # Additional contact
    ]
}

# Location Configuration
LOCATION_CONFIG = {
    'site_name': 'Women Safety Surveillance System',
    'location': 'Main Building - Ground Floor',
    'camera_id': 'CAM-001',
    'coordinates': {
        'latitude': 40.7128,    # Replace with actual coordinates
        'longitude': -74.0060
    }
}

# Alert Configuration
ALERT_CONFIG = {
    'snapshot_cooldown': 30,    # Seconds between snapshots (prevent spam)
    'max_daily_alerts': 50,     # Maximum alerts per day
    'alert_priority': 'CRITICAL',
    'auto_acknowledge': False,   # Whether to auto-acknowledge alerts
    
    # Image quality settings
    'image_quality': 95,        # JPEG quality (0-100)
    'enhance_images': True,     # Apply image enhancement
    'add_timestamp': True,      # Add timestamp overlay
    'add_location': True        # Add location overlay
}

# Notification Templates
EMAIL_TEMPLATE = """
🚨 EMERGENCY ALERT - WOMEN SAFETY CCTV SYSTEM 🚨

INCIDENT DETAILS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Incident ID: {incident_id}
• Alert Type: SOS Gesture Detection
• Gesture Type: {gesture_type}
• Detection Confidence: {confidence:.2f}
• Timestamp: {timestamp}
• Location: {location}
• Camera: {camera_id}

IMMEDIATE ACTION REQUIRED:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚠️  A person in distress has been detected in the surveillance area.
⚠️  This alert was automatically generated by AI-powered gesture recognition.
⚠️  Please respond immediately to verify the situation and provide assistance.

EVIDENCE:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📸 High-resolution snapshot is attached to this email as evidence.
📹 Video footage is being recorded and preserved.

RESPONSE GUIDELINES:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Immediately dispatch personnel to the location
2. Contact the person to verify their safety
3. If confirmed emergency, contact appropriate services
4. Acknowledge this alert in the system when responded
5. Document any actions taken

System Status: ACTIVE MONITORING
Alert Priority: CRITICAL
Response Time: IMMEDIATE

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This is an automated message from the Women Safety CCTV System.
For system support, contact: support@womensafety.system
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

SMS_TEMPLATE = """
🚨 WOMEN SAFETY ALERT 🚨
SOS gesture '{gesture_type}' detected with {confidence:.2f} confidence.
Location: {location}
Incident ID: {incident_id}
Time: {timestamp}
RESPOND IMMEDIATELY!
"""

# Development/Testing Configuration
DEVELOPMENT_CONFIG = {
    'test_mode': True,           # Set to False in production
    'mock_notifications': True,  # Don't send real notifications in test mode
    'save_test_snapshots': True, # Save snapshots even in test mode
    'log_all_events': True,      # Detailed logging for debugging
    'demo_contacts': [           # Safe contacts for testing
        'test@example.com',
        '+1-555-TEST'
    ]
}

# Security Configuration
SECURITY_CONFIG = {
    'encrypt_snapshots': False,   # Future: encrypt snapshot files
    'secure_transmission': True,  # Use TLS/SSL for email
    'audit_trail': True,         # Keep detailed audit logs
    'max_file_size': 10 * 1024 * 1024,  # 10MB max snapshot size
    'allowed_extensions': ['.jpg', '.jpeg', '.png']
}

# Instructions for Setup
SETUP_INSTRUCTIONS = """
EMERGENCY NOTIFICATION SETUP INSTRUCTIONS:
═══════════════════════════════════════════════════════════════════════════════

📧 EMAIL SETUP:
1. Create a dedicated Gmail account for the CCTV system
2. Enable 2-factor authentication
3. Generate an App Password (not your regular password)
4. Update EMAIL_CONFIG with your credentials
5. Add real authority email addresses

📱 SMS SETUP (Twilio):
1. Sign up for Twilio account (twilio.com)
2. Get Account SID and Auth Token from Twilio Console
3. Purchase a Twilio phone number
4. Update SMS_CONFIG with your credentials
5. Add real authority phone numbers

🔧 ALTERNATIVE SMS PROVIDERS:
• TextBelt: Simple HTTP API for SMS
• AWS SNS: Amazon's notification service
• Custom API: Integrate with your existing systems

⚠️  IMPORTANT SECURITY NOTES:
• Never commit credentials to version control
• Use environment variables in production
• Test thoroughly before deploying
• Keep contact information up to date
• Set up proper access controls

🧪 TESTING:
• Set test_mode = True for initial testing
• Use demo_contacts for safe testing
• Verify all notifications work properly
• Test with real SOS gestures

═══════════════════════════════════════════════════════════════════════════════
"""

if __name__ == "__main__":
    print(SETUP_INSTRUCTIONS)